name: Deploy backend pohodnik.tk
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy to pohodniki.tk
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.ETERNAL_SSH_HOST }}
          username: ${{ secrets.ETERNAL_SSH_USER }}
          key: ${{ secrets.ETERNAL_KEY }}
          script: |
            cd ~/
            rm -rf pohodnik-node-api
            git clone git@github.com:pohodnik/pohodnik-node-api.git
            sudo chmod -R 755 pohodnik-node-api
            cd pohodnik-node-api
            echo TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            docker-compose up -d
      - name: Send telegramm notofication
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_TO }} -d parse_mode=html -d text="$MESSAGE" >> /dev/null
        env:
          MESSAGE: |
            ✔ pohodnik-dode-bot succesfully deployed.
            https://pohodnik.tk
            <i>${{ github.event.head_commit.message }}</i>
            ${{ github.actor }}
