name: Deploy backend pohodnik.tk
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy to pohodnik.tk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: Prepare
        run: |
          echo "ARTIFACT_NAME=node_$(date +'%Y-%m-%d')-git.zip" >> $GITHUB_ENV
          echo $ARTIFACT_NAME
      - name: Zipping
        working-directory: ./src/
        run: zip -r ../${{ env.ARTIFACT_NAME }} *

      - name: Try FTP Login
        run: curl ftp://${{env.FTP_SERVER}}/ --user ${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}
        env:
          FTP_SERVER: ftp.fednik.ru

      - name: Send to ftp
        run: curl -T ${{ env.ARTIFACT_NAME }} -u ${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }} ftp://${{ env.FTP_SERVER }}/${{ env.REMOTE_FOLDER }}
        env:
          FTP_SERVER: ftp.fednik.ru
          REMOTE_FOLDER: deploy/

      - name: Unzip remote
        run: curl -i -X GET http://pohodnik.tk/unzip_node.php?name=${{ env.ARTIFACT_NAME }}

      - name: Send telegramm notofication
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_TO }} -d parse_mode=html -d text="$MESSAGE" >> /dev/null
        env:
          MESSAGE: |
            ✔ Backend succesfully deployed.
            https://pohodnik.tk
            <i>${{ github.event.head_commit.message }}</i>
            ${{ github.actor }}
