name: Deploy node backend pohodnik.tk
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy to pohodnik.tk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
        sudo chmod 600 ~/.ssh/private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
      shell: bash

      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    - name: Test
      run: ssh -T -i ~/.ssh/private.key thdwdvqs@185.253.217.253
      shell: bash

    - name: Send telegramm notofication
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_TO }} -d parse_mode=html -d text="$MESSAGE" >> /dev/null
      env:
          MESSAGE: |
            ✔ Backend succesfully deployed.
            https://pohodnik.tk
            <i>${{ github.event.head_commit.message }}</i>
            ${{ github.actor }}
